# Generated by Django 6.0.3 on 2026-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='products-images/0085.jpg', upload_to='products-images/'),
        ),
    ]
